- name: "wait 60 seconds for target connection to become reachable/usable."
  wait_for_connection:
    timeout: 60

- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"
    update_cache: yes

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Check version"
  shell: |
    node -v
    npm -v

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present