- name: "wait 600 seconds for target connection to become reachable/usable."
  ansible.builtin.wait_for_connection:
  timeout: 900
- name: Copy backend compressed file 
  become: true
  copy:
    src: /home/circleci/project/artifact.tar.gz
    dest: /home/ubuntu/backend/
- name: Extract backend files
  become: true
  shell: |
    cd /home/ubuntu/backend
    tar -vxf artifact.tar.gz
    rm artifact.tar.gz
- name : Compile and start app 
  become : true 
  shell : | 
    cd /home/ubuntu/backend
    sudo npm install
    
    pm2 stop default
    pm2 start npm -- start

